/* 
  *   Speech.java generated by speechmod 
 */

package Modalities;

import scxmlgen.interfaces.IModality;

public enum Speech implements IModality {

	HELP_SEARCH_MUSIC("[SPEECH][HELP][SEARCH_MUSIC]", 5000),
	PAUSE("[SPEECH][CONTROL_MUSIC][PAUSE]", 5000),
	PLAY("[SPEECH][CONTROL_MUSIC][RESUME]", 5000),
	VOLUME_UP("[SPEECH][ADJUST_VOLUME][UP]", 5000),
	QUIT("[SPEECH][GOODBYE]", 5000),
	SELECT("[SPEECH][SELECT]", 5000),
	NEXT_TRACK("[SPEECH][CHANGE_TRACK][NEXT]", 5000),
	PREVIOUS_TRACK("[SPEECH][CHANGE_TRACK][PREVIOUS]", 5000),
	VOLUME_DOWN("[SPEECH][ADJUST_VOLUME][DOWN]", 5000),

	;

	private String event;
	private int timeout;

	Speech(String m, int time) {
		event = m;
		timeout = time;
	}

	@Override
	public int getTimeOut() {
		return timeout;
	}

	@Override
	public String getEventName() {
		return event;
	}

	@Override
	public String getEvName() {
		return getModalityName().toLowerCase() + event.toLowerCase();
	}

}
