/* 
  *   Speech.java generated by speechmod 
 */

package Modalities;

import scxmlgen.interfaces.IModality;

public enum Speech implements IModality {

	HELP_SEARCH_MUSIC("[SPEECH][HELP_OPTION][SEARCH_MUSIC]", 1500),
	SEARCH_MUSIC("[SPEECH][SEARCH_MUSIC][MUSIC]", 1500),
	VOLUME_DOWN("[SPEECH][ADJUST_VOLUME][DOWN]", 1500),
	PAUSE("[SPEECH][CONTROL_MUSIC][PAUSE]", 1500),
	PLAY("[SPEECH][CONTROL_MUSIC][RESUME]", 1500),
	VOLUME_UP("[SPEECH][ADJUST_VOLUME][UP]", 1500),
	QUIT("[SPEECH][GOODBYE]", 1500),

	;

	private String event;
	private int timeout;

	Speech(String m, int time) {
		event = m;
		timeout = time;
	}

	@Override
	public int getTimeOut() {
		return timeout;
	}

	@Override
	public String getEventName() {
		return event;
	}

	@Override
	public String getEvName() {
		return getModalityName().toLowerCase() + event.toLowerCase();
	}

}
